In [1]:
import pandas as pd
import numpy as np
import nltk

nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\asus\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [2]:
datas = pd.read_csv('../ml/arxiv_papers_daily_fixed.csv')

In [3]:
datas

,id,title,authors,abstract,published_date,category,url,last_updated
0,2601.16953,Distribution of independent sets in perfect $r...,"Daniel Iľkovič, Jun Yan","Given a graph $G$, the family of all independe...",[Submitted on 23 Jan 2026],Combinatorics (math.CO),https://arxiv.org/abs/2601.16953,2026-01-27 17:52:59.692787
1,2601.17818,ViTCoP: Accelerating Large Vision-Language Mod...,"Wen Luo, Peng Chen, Xiaotao Huang, LiQun Huang",Large Vision-Language Models (LVLMs) incur hig...,[Submitted on 25 Jan 2026],Computer Vision and Pattern Recognition (cs.CV),https://arxiv.org/abs/2601.17818,2026-01-27 17:52:59.692787
2,2601.17999,Application of log-Chebyshev approximation and...,Nikolai Krivulin,We consider multicriteria problems of evaluati...,[Submitted on 25 Jan 2026],Optimization and Control (math.OC),https://arxiv.org/abs/2601.17999,2026-01-27 17:52:59.692787
3,2601.17573,Weakly and Strongly Admissible Triplets for a ...,Abderrahman Bouhamidi,"In this paper, we investigate a class of Colla...",[Submitted on 24 Jan 2026],General Mathematics (math.GM),https://arxiv.org/abs/2601.17573,2026-01-27 17:52:59.692787
4,2601.18304,On the inclusion of bounded harmonic functions...,"Yair Hartman, Aranka Hrušková, Omer Segev",We investigate the conditions under which the ...,[Submitted on 26 Jan 2026],Probability (math.PR),https://arxiv.org/abs/2601.18304,2026-01-27 17:52:59.692787
...,...,...,...,...,...,...,...,...
1278,2601.18303,Dicey Games: Shared Sources of Randomness in D...,"Léonard Brice, Thomas A. Henzinger, K. S. Thej...",Consider a 4-player version of Matching Pennie...,[Submitted on 26 Jan 2026],Computer Science and Game Theory (cs.GT),https://arxiv.org/abs/2601.18303,2026-01-27 17:52:59.692787
1279,2601.18513,LipNeXt: Scaling up Lipschitz-based Certified ...,"Kai Hu, Haoqi Hu, Matt Fredrikson",Lipschitz-based certification offers efficient...,[Submitted on 26 Jan 2026],Machine Learning (cs.LG),https://arxiv.org/abs/2601.18513,2026-01-27 17:52:59.692787
1280,2601.12441,The Dynamic and Endogenous Behavior of Re-Offe...,"Chuwen Zhang, Pengyi Shi, Amy Ward",Incarceration-diversion treatment programs aim...,[Submitted on 18 Jan 2026],Computers and Society (cs.CY),https://arxiv.org/abs/2601.12441,2026-01-27 17:52:59.692787
1281,2601.18240,V-Loop: Visual Logical Loop Verification for H...,"Mengyuan Jin, Zehui Liao, Yong Xia",Multimodal Large Language Models (MLLMs) have ...,[Submitted on 26 Jan 2026],Computer Vision and Pattern Recognition (cs.CV),https://arxiv.org/abs/2601.18240,2026-01-27 17:52:59.692787
1282,2601.16729,Derived equivalences for complexes with support,"K. Ganapathy, Sarang Sane",For a Serre subcategory $\mathscr L$ and a res...,[Submitted on 23 Jan 2026],Category Theory (math.CT),https://arxiv.org/abs/2601.16729,2026-01-27 17:52:59.692787

In [4]:
datas['title']

0       Distribution of independent sets in perfect $r...
1       ViTCoP: Accelerating Large Vision-Language Mod...
2       Application of log-Chebyshev approximation and...
3       Weakly and Strongly Admissible Triplets for a ...
4       On the inclusion of bounded harmonic functions...
                              ...
1278    Dicey Games: Shared Sources of Randomness in D...
1279    LipNeXt: Scaling up Lipschitz-based Certified ...
1280    The Dynamic and Endogenous Behavior of Re-Offe...
1281    V-Loop: Visual Logical Loop Verification for H...
1282      Derived equivalences for complexes with support
Name: title, Length: 1283, dtype: object

In [5]:
datas['category']

0                               Combinatorics (math.CO)
1       Computer Vision and Pattern Recognition (cs.CV)
2                    Optimization and Control (math.OC)
3                         General Mathematics (math.GM)
4                                 Probability (math.PR)
                             ...
1278           Computer Science and Game Theory (cs.GT)
1279                           Machine Learning (cs.LG)
1280                      Computers and Society (cs.CY)
1281    Computer Vision and Pattern Recognition (cs.CV)
1282                          Category Theory (math.CT)
Name: category, Length: 1283, dtype: object

In [6]:
datas['authors']

0                                 Daniel Iľkovič, Jun Yan
1          Wen Luo, Peng Chen, Xiaotao Huang, LiQun Huang
2                                        Nikolai Krivulin
3                                   Abderrahman Bouhamidi
4               Yair Hartman, Aranka Hrušková, Omer Segev
                              ...
1278    Léonard Brice, Thomas A. Henzinger, K. S. Thej...
1279                    Kai Hu, Haoqi Hu, Matt Fredrikson
1280                   Chuwen Zhang, Pengyi Shi, Amy Ward
1281                   Mengyuan Jin, Zehui Liao, Yong Xia
1282                            K. Ganapathy, Sarang Sane
Name: authors, Length: 1283, dtype: object

In [7]:
datas['abstract']

0       Given a graph $G$, the family of all independe...
1       Large Vision-Language Models (LVLMs) incur hig...
2       We consider multicriteria problems of evaluati...
3       In this paper, we investigate a class of Colla...
4       We investigate the conditions under which the ...
                              ...
1278    Consider a 4-player version of Matching Pennie...
1279    Lipschitz-based certification offers efficient...
1280    Incarceration-diversion treatment programs aim...
1281    Multimodal Large Language Models (MLLMs) have ...
1282    For a Serre subcategory $\mathscr L$ and a res...
Name: abstract, Length: 1283, dtype: object

In [8]:
datas['abstract'] = datas['abstract'].str.lower()

In [9]:
datas

,id,title,authors,abstract,published_date,category,url,last_updated
0,2601.16953,Distribution of independent sets in perfect $r...,"Daniel Iľkovič, Jun Yan","given a graph $g$, the family of all independe...",[Submitted on 23 Jan 2026],Combinatorics (math.CO),https://arxiv.org/abs/2601.16953,2026-01-27 17:52:59.692787
1,2601.17818,ViTCoP: Accelerating Large Vision-Language Mod...,"Wen Luo, Peng Chen, Xiaotao Huang, LiQun Huang",large vision-language models (lvlms) incur hig...,[Submitted on 25 Jan 2026],Computer Vision and Pattern Recognition (cs.CV),https://arxiv.org/abs/2601.17818,2026-01-27 17:52:59.692787
2,2601.17999,Application of log-Chebyshev approximation and...,Nikolai Krivulin,we consider multicriteria problems of evaluati...,[Submitted on 25 Jan 2026],Optimization and Control (math.OC),https://arxiv.org/abs/2601.17999,2026-01-27 17:52:59.692787
3,2601.17573,Weakly and Strongly Admissible Triplets for a ...,Abderrahman Bouhamidi,"in this paper, we investigate a class of colla...",[Submitted on 24 Jan 2026],General Mathematics (math.GM),https://arxiv.org/abs/2601.17573,2026-01-27 17:52:59.692787
4,2601.18304,On the inclusion of bounded harmonic functions...,"Yair Hartman, Aranka Hrušková, Omer Segev",we investigate the conditions under which the ...,[Submitted on 26 Jan 2026],Probability (math.PR),https://arxiv.org/abs/2601.18304,2026-01-27 17:52:59.692787
...,...,...,...,...,...,...,...,...
1278,2601.18303,Dicey Games: Shared Sources of Randomness in D...,"Léonard Brice, Thomas A. Henzinger, K. S. Thej...",consider a 4-player version of matching pennie...,[Submitted on 26 Jan 2026],Computer Science and Game Theory (cs.GT),https://arxiv.org/abs/2601.18303,2026-01-27 17:52:59.692787
1279,2601.18513,LipNeXt: Scaling up Lipschitz-based Certified ...,"Kai Hu, Haoqi Hu, Matt Fredrikson",lipschitz-based certification offers efficient...,[Submitted on 26 Jan 2026],Machine Learning (cs.LG),https://arxiv.org/abs/2601.18513,2026-01-27 17:52:59.692787
1280,2601.12441,The Dynamic and Endogenous Behavior of Re-Offe...,"Chuwen Zhang, Pengyi Shi, Amy Ward",incarceration-diversion treatment programs aim...,[Submitted on 18 Jan 2026],Computers and Society (cs.CY),https://arxiv.org/abs/2601.12441,2026-01-27 17:52:59.692787
1281,2601.18240,V-Loop: Visual Logical Loop Verification for H...,"Mengyuan Jin, Zehui Liao, Yong Xia",multimodal large language models (mllms) have ...,[Submitted on 26 Jan 2026],Computer Vision and Pattern Recognition (cs.CV),https://arxiv.org/abs/2601.18240,2026-01-27 17:52:59.692787
1282,2601.16729,Derived equivalences for complexes with support,"K. Ganapathy, Sarang Sane",for a serre subcategory $\mathscr l$ and a res...,[Submitted on 23 Jan 2026],Category Theory (math.CT),https://arxiv.org/abs/2601.16729,2026-01-27 17:52:59.692787

# Remove Formula for to make it easier to read

In [10]:
import re

def remove_hypen(abstract_series:pd.Series):
    return abstract_series.apply(lambda text: re.sub(r'[^\w\s]', '', str(text)))

In [11]:
datas['abstract']= remove_hypen(datas['abstract'])

In [12]:
datas['abstract']

0       given a graph g the family of all independent ...
1       large visionlanguage models lvlms incur high c...
2       we consider multicriteria problems of evaluati...
3       in this paper we investigate a class of collat...
4       we investigate the conditions under which the ...
                              ...
1278    consider a 4player version of matching pennies...
1279    lipschitzbased certification offers efficient ...
1280    incarcerationdiversion treatment programs aim ...
1281    multimodal large language models mllms have sh...
1282    for a serre subcategory mathscr l and a resolv...
Name: abstract, Length: 1283, dtype: object

In [ ]:
datas

,id,title,authors,abstract,published_date,category,url,last_updated
0,2601.16953,Distribution of independent sets in perfect $r...,"Daniel Iľkovič, Jun Yan",given a graph g the family of all independent ...,[Submitted on 23 Jan 2026],Combinatorics (math.CO),https://arxiv.org/abs/2601.16953,2026-01-27 17:52:59.692787
1,2601.17818,ViTCoP: Accelerating Large Vision-Language Mod...,"Wen Luo, Peng Chen, Xiaotao Huang, LiQun Huang",large visionlanguage models lvlms incur high c...,[Submitted on 25 Jan 2026],Computer Vision and Pattern Recognition (cs.CV),https://arxiv.org/abs/2601.17818,2026-01-27 17:52:59.692787
2,2601.17999,Application of log-Chebyshev approximation and...,Nikolai Krivulin,we consider multicriteria problems of evaluati...,[Submitted on 25 Jan 2026],Optimization and Control (math.OC),https://arxiv.org/abs/2601.17999,2026-01-27 17:52:59.692787
3,2601.17573,Weakly and Strongly Admissible Triplets for a ...,Abderrahman Bouhamidi,in this paper we investigate a class of collat...,[Submitted on 24 Jan 2026],General Mathematics (math.GM),https://arxiv.org/abs/2601.17573,2026-01-27 17:52:59.692787
4,2601.18304,On the inclusion of bounded harmonic functions...,"Yair Hartman, Aranka Hrušková, Omer Segev",we investigate the conditions under which the ...,[Submitted on 26 Jan 2026],Probability (math.PR),https://arxiv.org/abs/2601.18304,2026-01-27 17:52:59.692787
...,...,...,...,...,...,...,...,...
1278,2601.18303,Dicey Games: Shared Sources of Randomness in D...,"Léonard Brice, Thomas A. Henzinger, K. S. Thej...",consider a 4player version of matching pennies...,[Submitted on 26 Jan 2026],Computer Science and Game Theory (cs.GT),https://arxiv.org/abs/2601.18303,2026-01-27 17:52:59.692787
1279,2601.18513,LipNeXt: Scaling up Lipschitz-based Certified ...,"Kai Hu, Haoqi Hu, Matt Fredrikson",lipschitzbased certification offers efficient ...,[Submitted on 26 Jan 2026],Machine Learning (cs.LG),https://arxiv.org/abs/2601.18513,2026-01-27 17:52:59.692787
1280,2601.12441,The Dynamic and Endogenous Behavior of Re-Offe...,"Chuwen Zhang, Pengyi Shi, Amy Ward",incarcerationdiversion treatment programs aim ...,[Submitted on 18 Jan 2026],Computers and Society (cs.CY),https://arxiv.org/abs/2601.12441,2026-01-27 17:52:59.692787
1281,2601.18240,V-Loop: Visual Logical Loop Verification for H...,"Mengyuan Jin, Zehui Liao, Yong Xia",multimodal large language models mllms have sh...,[Submitted on 26 Jan 2026],Computer Vision and Pattern Recognition (cs.CV),https://arxiv.org/abs/2601.18240,2026-01-27 17:52:59.692787
1282,2601.16729,Derived equivalences for complexes with support,"K. Ganapathy, Sarang Sane",for a serre subcategory mathscr l and a resolv...,[Submitted on 23 Jan 2026],Category Theory (math.CT),https://arxiv.org/abs/2601.16729,2026-01-27 17:52:59.692787

In [14]:
datas['preprocessed_absract'] = datas['abstract']
datas

,id,title,authors,abstract,published_date,category,url,last_updated,preprocessed_absract
0,2601.16953,Distribution of independent sets in perfect $r...,"Daniel Iľkovič, Jun Yan",given a graph g the family of all independent ...,[Submitted on 23 Jan 2026],Combinatorics (math.CO),https://arxiv.org/abs/2601.16953,2026-01-27 17:52:59.692787,given a graph g the family of all independent ...
1,2601.17818,ViTCoP: Accelerating Large Vision-Language Mod...,"Wen Luo, Peng Chen, Xiaotao Huang, LiQun Huang",large visionlanguage models lvlms incur high c...,[Submitted on 25 Jan 2026],Computer Vision and Pattern Recognition (cs.CV),https://arxiv.org/abs/2601.17818,2026-01-27 17:52:59.692787,large visionlanguage models lvlms incur high c...
2,2601.17999,Application of log-Chebyshev approximation and...,Nikolai Krivulin,we consider multicriteria problems of evaluati...,[Submitted on 25 Jan 2026],Optimization and Control (math.OC),https://arxiv.org/abs/2601.17999,2026-01-27 17:52:59.692787,we consider multicriteria problems of evaluati...
3,2601.17573,Weakly and Strongly Admissible Triplets for a ...,Abderrahman Bouhamidi,in this paper we investigate a class of collat...,[Submitted on 24 Jan 2026],General Mathematics (math.GM),https://arxiv.org/abs/2601.17573,2026-01-27 17:52:59.692787,in this paper we investigate a class of collat...
4,2601.18304,On the inclusion of bounded harmonic functions...,"Yair Hartman, Aranka Hrušková, Omer Segev",we investigate the conditions under which the ...,[Submitted on 26 Jan 2026],Probability (math.PR),https://arxiv.org/abs/2601.18304,2026-01-27 17:52:59.692787,we investigate the conditions under which the ...
...,...,...,...,...,...,...,...,...,...
1278,2601.18303,Dicey Games: Shared Sources of Randomness in D...,"Léonard Brice, Thomas A. Henzinger, K. S. Thej...",consider a 4player version of matching pennies...,[Submitted on 26 Jan 2026],Computer Science and Game Theory (cs.GT),https://arxiv.org/abs/2601.18303,2026-01-27 17:52:59.692787,consider a 4player version of matching pennies...
1279,2601.18513,LipNeXt: Scaling up Lipschitz-based Certified ...,"Kai Hu, Haoqi Hu, Matt Fredrikson",lipschitzbased certification offers efficient ...,[Submitted on 26 Jan 2026],Machine Learning (cs.LG),https://arxiv.org/abs/2601.18513,2026-01-27 17:52:59.692787,lipschitzbased certification offers efficient ...
1280,2601.12441,The Dynamic and Endogenous Behavior of Re-Offe...,"Chuwen Zhang, Pengyi Shi, Amy Ward",incarcerationdiversion treatment programs aim ...,[Submitted on 18 Jan 2026],Computers and Society (cs.CY),https://arxiv.org/abs/2601.12441,2026-01-27 17:52:59.692787,incarcerationdiversion treatment programs aim ...
1281,2601.18240,V-Loop: Visual Logical Loop Verification for H...,"Mengyuan Jin, Zehui Liao, Yong Xia",multimodal large language models mllms have sh...,[Submitted on 26 Jan 2026],Computer Vision and Pattern Recognition (cs.CV),https://arxiv.org/abs/2601.18240,2026-01-27 17:52:59.692787,multimodal large language models mllms have sh...
1282,2601.16729,Derived equivalences for complexes with support,"K. Ganapathy, Sarang Sane",for a serre subcategory mathscr l and a resolv...,[Submitted on 23 Jan 2026],Category Theory (math.CT),https://arxiv.org/abs/2601.16729,2026-01-27 17:52:59.692787,for a serre subcategory mathscr l and a resolv...

In [15]:
from nltk.tokenize import word_tokenize



datas['preprocessed_absract']=datas['preprocessed_absract'].apply(lambda x:word_tokenize(x))

In [16]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(datas['preprocessed_absract'].apply(lambda x: ' '.join(x)))

tf_df = pd.DataFrame(
    X.toarray(), # type: ignore
    columns=vectorizer.get_feature_names_out()
).T

tf_df.columns = [f'D{i+1}' for i in range(len(tf_df.columns))]
tf_df = tf_df.reset_index().rename(columns={'index': 'Kata'})
tf_df.insert(0, 'No', range(1, len(tf_df) + 1))

tf_df

,No,Kata,D1,D2,D3,D4,D5,D6,D7,D8,...,D1274,D1275,D1276,D1277,D1278,D1279,D1280,D1281,D1282,D1283
0,1,0001,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,0036,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,3,006,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,00870295,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,01,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18400,18401,zynq,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18401,18402,zz_inftyx,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18402,18403,étale,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18403,18404,łojasiewiczsimon,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18404,18405,łukasiewicz,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
datas

,id,title,authors,abstract,published_date,category,url,last_updated,preprocessed_absract
0,2601.16953,Distribution of independent sets in perfect $r...,"Daniel Iľkovič, Jun Yan",given a graph g the family of all independent ...,[Submitted on 23 Jan 2026],Combinatorics (math.CO),https://arxiv.org/abs/2601.16953,2026-01-27 17:52:59.692787,"[given, a, graph, g, the, family, of, all, ind..."
1,2601.17818,ViTCoP: Accelerating Large Vision-Language Mod...,"Wen Luo, Peng Chen, Xiaotao Huang, LiQun Huang",large visionlanguage models lvlms incur high c...,[Submitted on 25 Jan 2026],Computer Vision and Pattern Recognition (cs.CV),https://arxiv.org/abs/2601.17818,2026-01-27 17:52:59.692787,"[large, visionlanguage, models, lvlms, incur, ..."
2,2601.17999,Application of log-Chebyshev approximation and...,Nikolai Krivulin,we consider multicriteria problems of evaluati...,[Submitted on 25 Jan 2026],Optimization and Control (math.OC),https://arxiv.org/abs/2601.17999,2026-01-27 17:52:59.692787,"[we, consider, multicriteria, problems, of, ev..."
3,2601.17573,Weakly and Strongly Admissible Triplets for a ...,Abderrahman Bouhamidi,in this paper we investigate a class of collat...,[Submitted on 24 Jan 2026],General Mathematics (math.GM),https://arxiv.org/abs/2601.17573,2026-01-27 17:52:59.692787,"[in, this, paper, we, investigate, a, class, o..."
4,2601.18304,On the inclusion of bounded harmonic functions...,"Yair Hartman, Aranka Hrušková, Omer Segev",we investigate the conditions under which the ...,[Submitted on 26 Jan 2026],Probability (math.PR),https://arxiv.org/abs/2601.18304,2026-01-27 17:52:59.692787,"[we, investigate, the, conditions, under, whic..."
...,...,...,...,...,...,...,...,...,...
1278,2601.18303,Dicey Games: Shared Sources of Randomness in D...,"Léonard Brice, Thomas A. Henzinger, K. S. Thej...",consider a 4player version of matching pennies...,[Submitted on 26 Jan 2026],Computer Science and Game Theory (cs.GT),https://arxiv.org/abs/2601.18303,2026-01-27 17:52:59.692787,"[consider, a, 4player, version, of, matching, ..."
1279,2601.18513,LipNeXt: Scaling up Lipschitz-based Certified ...,"Kai Hu, Haoqi Hu, Matt Fredrikson",lipschitzbased certification offers efficient ...,[Submitted on 26 Jan 2026],Machine Learning (cs.LG),https://arxiv.org/abs/2601.18513,2026-01-27 17:52:59.692787,"[lipschitzbased, certification, offers, effici..."
1280,2601.12441,The Dynamic and Endogenous Behavior of Re-Offe...,"Chuwen Zhang, Pengyi Shi, Amy Ward",incarcerationdiversion treatment programs aim ...,[Submitted on 18 Jan 2026],Computers and Society (cs.CY),https://arxiv.org/abs/2601.12441,2026-01-27 17:52:59.692787,"[incarcerationdiversion, treatment, programs, ..."
1281,2601.18240,V-Loop: Visual Logical Loop Verification for H...,"Mengyuan Jin, Zehui Liao, Yong Xia",multimodal large language models mllms have sh...,[Submitted on 26 Jan 2026],Computer Vision and Pattern Recognition (cs.CV),https://arxiv.org/abs/2601.18240,2026-01-27 17:52:59.692787,"[multimodal, large, language, models, mllms, h..."
1282,2601.16729,Derived equivalences for complexes with support,"K. Ganapathy, Sarang Sane",for a serre subcategory mathscr l and a resolv...,[Submitted on 23 Jan 2026],Category Theory (math.CT),https://arxiv.org/abs/2601.16729,2026-01-27 17:52:59.692787,"[for, a, serre, subcategory, mathscr, l, and, ..."

In [ ]:
from nltk.stem.porter import PorterStemmer
stemmer = PorterStemmer()

# abstracts are tokenized (lists of tokens); stem each token instead of trying to stem the list
# datas['preprocessed_absract'] = datas['preprocessed_abstract'].apply(lambda tokens: [stemmer.stem(t) for t in tokens])
datas['preprocessed_absract']=datas['preprocessed_absract'].apply(lambda x:[stemmer.stem(t)for t in x])

In [ ]:
datas['preprocessed_absract']

0       [given, a, graph, g, the, famili, of, all, ind...
1       [larg, visionlanguag, model, lvlm, incur, high...
2       [we, consid, multicriteria, problem, of, evalu...
3       [in, thi, paper, we, investig, a, class, of, c...
4       [we, investig, the, condit, under, which, the,...
                              ...
1278    [consid, a, 4player, version, of, match, penni...
1279    [lipschitzbas, certif, offer, effici, determin...
1280    [incarcerationdivers, treatment, program, aim,...
1281    [multimod, larg, languag, model, mllm, have, s...
1282    [for, a, serr, subcategori, mathscr, l, and, a...
Name: preprocessed_absract, Length: 1283, dtype: object

In [ ]:
datas

,id,title,authors,abstract,published_date,category,url,last_updated,preprocessed_absract
0,2601.16953,Distribution of independent sets in perfect $r...,"Daniel Iľkovič, Jun Yan",given a graph g the family of all independent ...,[Submitted on 23 Jan 2026],Combinatorics (math.CO),https://arxiv.org/abs/2601.16953,2026-01-27 17:52:59.692787,"[given, a, graph, g, the, famili, of, all, ind..."
1,2601.17818,ViTCoP: Accelerating Large Vision-Language Mod...,"Wen Luo, Peng Chen, Xiaotao Huang, LiQun Huang",large visionlanguage models lvlms incur high c...,[Submitted on 25 Jan 2026],Computer Vision and Pattern Recognition (cs.CV),https://arxiv.org/abs/2601.17818,2026-01-27 17:52:59.692787,"[larg, visionlanguag, model, lvlm, incur, high..."
2,2601.17999,Application of log-Chebyshev approximation and...,Nikolai Krivulin,we consider multicriteria problems of evaluati...,[Submitted on 25 Jan 2026],Optimization and Control (math.OC),https://arxiv.org/abs/2601.17999,2026-01-27 17:52:59.692787,"[we, consid, multicriteria, problem, of, evalu..."
3,2601.17573,Weakly and Strongly Admissible Triplets for a ...,Abderrahman Bouhamidi,in this paper we investigate a class of collat...,[Submitted on 24 Jan 2026],General Mathematics (math.GM),https://arxiv.org/abs/2601.17573,2026-01-27 17:52:59.692787,"[in, thi, paper, we, investig, a, class, of, c..."
4,2601.18304,On the inclusion of bounded harmonic functions...,"Yair Hartman, Aranka Hrušková, Omer Segev",we investigate the conditions under which the ...,[Submitted on 26 Jan 2026],Probability (math.PR),https://arxiv.org/abs/2601.18304,2026-01-27 17:52:59.692787,"[we, investig, the, condit, under, which, the,..."
...,...,...,...,...,...,...,...,...,...
1278,2601.18303,Dicey Games: Shared Sources of Randomness in D...,"Léonard Brice, Thomas A. Henzinger, K. S. Thej...",consider a 4player version of matching pennies...,[Submitted on 26 Jan 2026],Computer Science and Game Theory (cs.GT),https://arxiv.org/abs/2601.18303,2026-01-27 17:52:59.692787,"[consid, a, 4player, version, of, match, penni..."
1279,2601.18513,LipNeXt: Scaling up Lipschitz-based Certified ...,"Kai Hu, Haoqi Hu, Matt Fredrikson",lipschitzbased certification offers efficient ...,[Submitted on 26 Jan 2026],Machine Learning (cs.LG),https://arxiv.org/abs/2601.18513,2026-01-27 17:52:59.692787,"[lipschitzbas, certif, offer, effici, determin..."
1280,2601.12441,The Dynamic and Endogenous Behavior of Re-Offe...,"Chuwen Zhang, Pengyi Shi, Amy Ward",incarcerationdiversion treatment programs aim ...,[Submitted on 18 Jan 2026],Computers and Society (cs.CY),https://arxiv.org/abs/2601.12441,2026-01-27 17:52:59.692787,"[incarcerationdivers, treatment, program, aim,..."
1281,2601.18240,V-Loop: Visual Logical Loop Verification for H...,"Mengyuan Jin, Zehui Liao, Yong Xia",multimodal large language models mllms have sh...,[Submitted on 26 Jan 2026],Computer Vision and Pattern Recognition (cs.CV),https://arxiv.org/abs/2601.18240,2026-01-27 17:52:59.692787,"[multimod, larg, languag, model, mllm, have, s..."
1282,2601.16729,Derived equivalences for complexes with support,"K. Ganapathy, Sarang Sane",for a serre subcategory mathscr l and a resolv...,[Submitted on 23 Jan 2026],Category Theory (math.CT),https://arxiv.org/abs/2601.16729,2026-01-27 17:52:59.692787,"[for, a, serr, subcategori, mathscr, l, and, a..."

In [ ]:
arxiv_paper = pd.DataFrame(datas)

arxiv_paper

,id,title,authors,abstract,published_date,category,url,last_updated,preprocessed_absract
0,2601.16953,Distribution of independent sets in perfect $r...,"Daniel Iľkovič, Jun Yan",given a graph g the family of all independent ...,[Submitted on 23 Jan 2026],Combinatorics (math.CO),https://arxiv.org/abs/2601.16953,2026-01-27 17:52:59.692787,"[given, a, graph, g, the, famili, of, all, ind..."
1,2601.17818,ViTCoP: Accelerating Large Vision-Language Mod...,"Wen Luo, Peng Chen, Xiaotao Huang, LiQun Huang",large visionlanguage models lvlms incur high c...,[Submitted on 25 Jan 2026],Computer Vision and Pattern Recognition (cs.CV),https://arxiv.org/abs/2601.17818,2026-01-27 17:52:59.692787,"[larg, visionlanguag, model, lvlm, incur, high..."
2,2601.17999,Application of log-Chebyshev approximation and...,Nikolai Krivulin,we consider multicriteria problems of evaluati...,[Submitted on 25 Jan 2026],Optimization and Control (math.OC),https://arxiv.org/abs/2601.17999,2026-01-27 17:52:59.692787,"[we, consid, multicriteria, problem, of, evalu..."
3,2601.17573,Weakly and Strongly Admissible Triplets for a ...,Abderrahman Bouhamidi,in this paper we investigate a class of collat...,[Submitted on 24 Jan 2026],General Mathematics (math.GM),https://arxiv.org/abs/2601.17573,2026-01-27 17:52:59.692787,"[in, thi, paper, we, investig, a, class, of, c..."
4,2601.18304,On the inclusion of bounded harmonic functions...,"Yair Hartman, Aranka Hrušková, Omer Segev",we investigate the conditions under which the ...,[Submitted on 26 Jan 2026],Probability (math.PR),https://arxiv.org/abs/2601.18304,2026-01-27 17:52:59.692787,"[we, investig, the, condit, under, which, the,..."
...,...,...,...,...,...,...,...,...,...
1278,2601.18303,Dicey Games: Shared Sources of Randomness in D...,"Léonard Brice, Thomas A. Henzinger, K. S. Thej...",consider a 4player version of matching pennies...,[Submitted on 26 Jan 2026],Computer Science and Game Theory (cs.GT),https://arxiv.org/abs/2601.18303,2026-01-27 17:52:59.692787,"[consid, a, 4player, version, of, match, penni..."
1279,2601.18513,LipNeXt: Scaling up Lipschitz-based Certified ...,"Kai Hu, Haoqi Hu, Matt Fredrikson",lipschitzbased certification offers efficient ...,[Submitted on 26 Jan 2026],Machine Learning (cs.LG),https://arxiv.org/abs/2601.18513,2026-01-27 17:52:59.692787,"[lipschitzbas, certif, offer, effici, determin..."
1280,2601.12441,The Dynamic and Endogenous Behavior of Re-Offe...,"Chuwen Zhang, Pengyi Shi, Amy Ward",incarcerationdiversion treatment programs aim ...,[Submitted on 18 Jan 2026],Computers and Society (cs.CY),https://arxiv.org/abs/2601.12441,2026-01-27 17:52:59.692787,"[incarcerationdivers, treatment, program, aim,..."
1281,2601.18240,V-Loop: Visual Logical Loop Verification for H...,"Mengyuan Jin, Zehui Liao, Yong Xia",multimodal large language models mllms have sh...,[Submitted on 26 Jan 2026],Computer Vision and Pattern Recognition (cs.CV),https://arxiv.org/abs/2601.18240,2026-01-27 17:52:59.692787,"[multimod, larg, languag, model, mllm, have, s..."
1282,2601.16729,Derived equivalences for complexes with support,"K. Ganapathy, Sarang Sane",for a serre subcategory mathscr l and a resolv...,[Submitted on 23 Jan 2026],Category Theory (math.CT),https://arxiv.org/abs/2601.16729,2026-01-27 17:52:59.692787,"[for, a, serr, subcategori, mathscr, l, and, a..."

In [ ]:
arxiv_paper.to_csv('arxiv_paper_preprocessed.csv')